config/routes.rb
Madmon::Application.routes.draw do
  root to: "datapoints#index"
  resources :datapoints
  resources :watches do
    resources :datapoints
  end
end

app/models/datapoint.rb
class Datapoint < ActiveRecord::Base
  belongs_to :watch
end

app/models/ping_watch.rb
class PingWatch < Watch
  def self.model_name
    Watch.model_name
  end

  def self.configuration_options
    [:host]
  end

  def tick
    self.datapoints.create(value: PingWatch.parse_ping_to_ms(ping_output))
  end

  def ping_output
    `ping -c1 #{config[:host]}`
  end

  def self.parse_ping_to_ms(ping_output)
    matches = ping_output.match(/time=(\d+\.?\d+)/)
    if (matches)
      matches[1].to_f
    else
      -1
    end
  end
end

app/models/random_watch.rb
require_dependency 'datapoint'
class RandomWatch < Watch
  MIN_MOD = 0.1
  MAX_MOD = 0.2

  after_initialize do
    @r = Random.new
  end

  def self.model_name
    Watch.model_name
  end


  def tick
    if self.datapoints.empty?
      random_value = 42
    else
      last_value = self.datapoints.last.value

      before_last_value = self.datapoints.all[self.datapoints.count-2].value
      mod = before_last_value > last_value ? 0.15 : -0.15

      modifier = @r.rand MIN_MOD..MAX_MOD
      if rand > (0.5 + mod)
        random_value = last_value + modifier*last_value
      else
        random_value = last_value - modifier*last_value
      end
    end
    self.datapoints.create(value: random_value)
  end

  def seed(number=20)
    number.times do 
      dp = tick
      dp.created_at = self.datapoints.last.created_at + 1.second
      dp.save
    end
  end
end

app/models/watch.rb
class Watch < ActiveRecord::Base
  has_many :datapoints
  serialize :config
  after_initialize do
    self.config ||= {}
  end

  def self.configuration_options
    []
  end

  # This should create a single datapoint somehow
  def tick
    raise NotImplementedError
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/datapoints_controller.rb
class DatapointsController < ApplicationController

  def index
    unless params[:watch_id].blank?
      @watch = Watch.find(params[:watch_id])
      @datapoints = @watch.datapoints
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  before_action :set_watch, only: [:show, :edit, :update, :destroy]

  # GET /watches
  # GET /watches.json
  def index
    @watches = Watch.all
  end

  # GET /watches/1
  # GET /watches/1.json
  def show
  end

  # GET /watches/new
  def new
    @watch = Watch.new
  end

  # GET /watches/1/edit
  def edit
  end

  # POST /watches
  # POST /watches.json
  def create
    @watch = Watch.new(watch_params)

    respond_to do |format|
      if @watch.save
        format.html { redirect_to @watch, notice: 'Watch was successfully created.' }
        format.json { render action: 'show', status: :created, location: @watch }
      else
        format.html { render action: 'new' }
        format.json { render json: @watch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watches/1
  # PATCH/PUT /watches/1.json
  def update
    respond_to do |format|
      if @watch.update(watch_params)
        format.html { redirect_to @watch, notice: 'Watch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @watch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watches/1
  # DELETE /watches/1.json
  def destroy
    @watch.destroy
    respond_to do |format|
      format.html { redirect_to watches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watch
      @watch = Watch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def watch_params
      params.require(:watch).permit(:name, :frequency)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datapoints_helper.rb
module DatapointsHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/datapoints/_chart.haml
-# locals: watch
%div{id: "watch-chart-#{watch.id}"}

:coffeescript
  $(document).ready ->
    new Madmon.DatapointsChartsPage
      watch_id: #{watch.id}
      el: "#watch-chart-#{watch.id}"

app/views/datapoints/index.html.haml
%h1 MadMon
- Watch.all.each do |watch|
  .valueOverTime
    %h3= watch.name
    = render partial: "datapoints/chart", locals: {watch: watch}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Madmon</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= stylesheet_link_tag "/dc.css" %>
  <%= javascript_include_tag "/d3.js" %>
  <%= javascript_include_tag "/crossfilter.js" %>
  <%= javascript_include_tag "/dc.js" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/watches/_form.html.haml
= form_for @watch do |f|
  - if @watch.errors.any?
    #error_explanation
      %h2= "#{pluralize(@watch.errors.count, "error")} prohibited this watch from being saved:"
      %ul
        - @watch.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
    
  .field
    = f.label :frequency
    = f.number_field :frequency
  .actions
    = f.submit 'Save'

app/views/watches/edit.html.haml
%h1 Editing watch

= render 'form'

= link_to 'Show', @watch
\|
= link_to 'Back', watches_path

app/views/watches/index.html.haml
%h1 Listing watches

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @watches.each do |watch|
    %tr
      %td= watch.name
      %td= link_to 'Show', watch
      %td= link_to 'Edit', edit_watch_path(watch)
      %td= link_to 'Destroy', watch, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Watch', new_watch_path

app/views/watches/new.html.haml
%h1 New watch

= render 'form'

= link_to 'Back', watches_path

app/views/watches/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @watch.name


= render partial: "datapoints/chart", locals: {watch: @watch}

= link_to 'Edit', edit_watch_path(@watch)
\|
= link_to 'Back', watches_path